# Generated by Django 5.2.7 on 2025-10-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_project_created_at_remove_project_developer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Company')),
                ('service', models.CharField(choices=[('web', 'Web Design'), ('automation', 'Agentic Automation'), ('marketing', 'Marketing & Growth'), ('consulting', 'Consulting'), ('other', 'Other')], max_length=20, verbose_name='Service Interest')),
                ('budget', models.CharField(choices=[('less-2k', 'Less than $2K'), ('2-5k', '$2K - $5K'), ('5-10k', '$5K - $10K'), ('10-25k', '$10K - $25K'), ('25k+', '$25K+')], max_length=20, verbose_name='Budget Range')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
