# Generated by Django 5.2.7 on 2026-01-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_category_tag_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Subscription')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Subscribed At')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Unsubscribed At')),
                ('emails_sent', models.PositiveIntegerField(default=0, verbose_name='Emails Sent')),
                ('emails_opened', models.PositiveIntegerField(default=0, verbose_name='Emails Opened')),
                ('last_email_sent', models.DateTimeField(blank=True, null=True, verbose_name='Last Email Sent')),
                ('source', models.CharField(default='blog', help_text='Where they subscribed from (blog, homepage, etc.)', max_length=50, verbose_name='Subscription Source')),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
